apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opa
  name: opa
  namespace: opa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opa
    spec:
      containers:
      - image: openpolicyagent/opa
        name: opa
        args: 
        - run
        - --server
        - --addr
        - :8181
